### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by demlasjr**

### CODE REVIEW

**Comment by onericcomputing** [comment]
Hi,
I see you work hard. Here is the current file I have for 2.0 branch. I forgot to update the git repo. My apologies.
Please copy paste what you did before missing strings. Please add your name and branding on the top, as official contributor 


Thanks
Eric

**Comment by demlasjr** [comment]
Uhmmm...sorry, where is the 2.0 branch ? I don't see it yet.

**Comment by onericcomputing** [comment]
> Uhmmm...sorry, where is the 2.0 branch ? I don't see it yet.

:-) this is the 2.0 branch

**Review by onericcomputing — APPROVED** [review]

**Comment by demlasjr** [comment]
Oh, I thought that there are missing strings which are not yet translated, I don't understand your "Please copy paste what you did before missing strings.". Sorry, probably I'm tired. 
I'll add my name on the top.

**Comment by onericcomputing** [comment]
Yes, because you changed many things, idea is check the last string of your translation and copy from my file the whole missing portion :-)

Thanks. 
Eric Claver AKAFFOU

**Comment by demlasjr** [comment]
Oh got it! You mean differences between the english and spanish version of file, I just diff'ed the files!

But there are also lines which are available in spanish version but not on english version. Should I merge both with the missing strings or just the spanish one?

**Comment by onericcomputing** [comment]
Yes, i saw also. You can merge. I will update all files next days. 

Thanks. 
Eric Claver AKAFFOU

**Comment by onericcomputing** [comment]
People sometimes remove what they don’t need, so I copy paste as I can :-)

Cordialement 
Eric Claver AKAFFOU

**Comment by demlasjr** [comment]
I just checked the english file, in facts it doesn't missing anything, there are text which isn't added in the same order as in spanish file, that's the only difference, but the file is good

**Comment by onericcomputing** [comment]
Great 👍🏿 ! Many people worked on the file and sometimes they remove what they did not use. Thanks

**Comment by demlasjr** [comment]
That's great mate, I've checked the demo and looks good so far but there are still some string missing in the menu :(

[https://i.imgur.com/ndp2pA1.png](url)

**Comment by onericcomputing** [comment]
Thanks. If you want i can setup a ftp access to language folder for live edit. Let me know.

**Comment by demlasjr** [comment]
That's great. Then I will only need to know the strings name in order to traslate, but tomorrow I plan to buy the script already so I can help to the development

**Comment by onericcomputing** [comment]
Ok thanks man! This night I will import the change for the Spanish surcharge. I was wondering how to implement it: automatic detection when company address is « Spain » but you told me Canadian 🇨🇦 need the same and maybe other countries. So I don’t know. Manual setup and option to enable maybe. Let me know your thoughts

**Comment by demlasjr** [comment]
Sorry for the late answer and not having bought the script already, I just reached my home after a hard day. 
First, yes, I think the manual way will be just great, since geoip free database isn't always accurate and the other solution will be an installer, when you first configure the script, to enable or not those features, but again, there are others countries which can use it and we need to find out which ones apart Spain and Canada. 
The manual solution I guess is the great and the easiest but maybe you should add an option to enable one or both of the options and maybe rename them, since in Canada it's called differently than in Spain, so a final user can rename it easily without editing translations files.

Tomorrow I try to buy, install and finish the translations, but I cannot promise since I still have a lot of things to do (I'm late after the health issues I had) and this weekend I'm teaching people repairing electronics. If I will cannot do it, Monday I will do it for sure.


PS: Please don't forget to add those surcharges on Tax reports also please.

Thanks.

Regards,
Laszlo

**Comment by onericcomputing** [comment]
Hi,
I hope you are fine. Just a quick message to inform that the system is almost done. Just to need to build reports. You can test if you have time. 
Thanks

Eric

**Pull request merged**
